### PR TITLE
cleanup `walkDirectory`

### PR DESCRIPTION
**Pull request by themattchan**
@ranjitjhala looks like `Language.Mist.Runner` is not checked in...

### CODE REVIEW

**Comment by ranjitjhala** [comment]
oops, I just added it, thanks for the heads up @themattchan !

**Comment by ranjitjhala** [comment]
thanks a bunch!

**Comment by themattchan** [comment]
glad that this worked, I didn't even typecheck it!

**Comment by ranjitjhala** [comment]
oops .. I assumed you had :) let me check... it does! :)

**Pull request merged**
