### PR TITLE
Split Core into Core and ANFCore.

### PR DESCRIPTION
**Pull request by mkolosick**
ANFCore is a "refinement" of Core such that
applications are in ANF form.

### CODE REVIEW

**Comment by atondwal** [comment]
I think this might actually be incompatible with the variable-arity prims, hmm... 
```
atondwal@anish-kudu> stack exec -- liquid lib/Language/Mist/Utils.hs lib/Language/Mist/UX.hs lib/Language/Mist/Types.hs                                                                                   ~/src/mist
LiquidHaskell Version 0.8.4.0, Git revision c60759b646d06954188474a7a75dc2083f957429 (dirty)
Copyright 2013-18 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************


**** DONE:  A-Normalization ****************************************************


**** DONE:  A-Normalization ****************************************************


**** DONE:  annotate ***********************************************************


**** RESULT: ERROR *************************************************************


 <no source information>:0:0: Error: Illegal type specification for `GHC.Types.[]`
     GHC.Types.[] :: forall a##xo <p :: a##xo a##xo -> Bool> .
                     {VV : [a##xo]<\_ VV -> {VV : _<p> | true}> | len VV == 0
                                                                  && (isVarAll VV <=> true)}
     Sort Error in Refinement: {VV : [a##11] | (len VV == 0
                                                && (Language.Mist.Types.isVarAll VV <=> true))}
     Cannot unify a##11 with (Language.Mist.Types.Core @(46)) in expression: Language.Mist.Types.isVarAll VV << ceq2 >>


 <no source information>:0:0: Error: Illegal type specification for `GHC.Types.:`
     GHC.Types.: :: forall a##xo <p :: a##xo a##xo -> Bool> .
                    head:a##xo
                    -> tail:[{VV : a##xo<p head> | true}]<\_ VV -> {VV : _<p> | true}>
                       -> {VV : [a##xo]<\_ VV -> {VV : _<p> | true}> | tail VV == tail
                                                                       && head VV == head
                                                                       && len VV == 1 + len tail
                                                                       && (isVarAll VV <=> isVar head
                                                                                           && isVarAll tail)}
     Sort Error in Refinement: {VV : [a##11] | (((tail VV == tail##GHC.Types.:
                                                  && head VV == head##GHC.Types.:)
                                                 && len VV == 1 + len tail##GHC.Types.:)
                                                && (Language.Mist.Types.isVarAll VV <=> Language.Mist.Types.isVar head##GHC.Types.:
                                                                                        && Language.Mist.Types.isVarAll tail##GHC.Types.:))}
     Cannot unify a##11 with (Language.Mist.Types.Core @(54)) in expression: Language.Mist.Types.isVarAll VV << ceq2 >>
```

**Comment by atondwal** [comment]
(we should eventually set up some CI...)

**Comment by mkolosick** [comment]
Can you read that to me?

**Comment by atondwal** [comment]
The error message? It's mysterious to me too; suffice to say it hits upon a bug in the liquidhaskell elaborator. I think it's probably something to do with lists; it shouldn't show up for the Prim2 version since we just `&&` the recursive calls on the two subexprs.

**Comment by mkolosick** [comment]
Decided to design Core later after we have worked out the relevant issues.

**Comment by ranjitjhala** [comment]
Confused — what is connection between this and LH/GHC core?

**Comment by atondwal** [comment]
Just analogy; a Core is just a fully elaborated Expr (with explicit Tapp,
tabs, types at binders)

**Pull request closed without merging**
